version: '3'

services:
  api:
    image: linkextractor-api:step6-ruby
    build: ./api-rb
    ports:
      - "4567:4567"
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./logs:/app/logs

  redis:
    image: redis

  locust:
    image: locustio/locust
    volumes:
      - ./locustfile.py:/mnt/locust/locustfile.py
    ports:
      - "8089:8089"
    command: -f /mnt/locust/locustfile.py --users 1000 --host http://api:4567
    depends_on:
      - api
